---
title: "Soccult Exam Analysis"
author: "Lina Elkjær Pedersen og Thea Pedersen"
date: "5/6/2021"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}

library(tidyverse)
library(ggplot2)
library(dplyr)

```

#PART 1: Data Cleaning

Here we remove the colums that we do not need, make a new column to categorize the four scenario types, and more.

Firstly, we import the data 

```{r data cleaning}

# saving list of all file names in the SC_exam_data folder in my working directory
list <- list.files(path = "./data", pattern = ".csv", all.files = FALSE, full.names = TRUE)



# We create a function for reading the data files and creating the relevant columns:
read_files <- function(filename) {
    # load data
    data1 <- read.csv(file = filename)
    
    #Changing the weird names
    names(data1)[names(data1) == "Initialer..f.eks..TP.."] <- "ID"
    names(data1)[names(data1) == "trials.thisN"] <- "Trial"
    names(data1)[names(data1) == "Alder..f.eks..20..."] <- "Age"
    names(data1)[names(data1) == "Køn..mand.kvinde.andet.."] <- "Gender_par"
    names(data1)[names(data1) == "slider.response"] <- "Trust_rating"
    
    #Creating new columns for Stimulus_type and Scenario_type
    data1$Stimulus_type <- data1$stimuli
    data1$Scenario_type_specific <- data1$scenario
    
    #Calling all the MJ "male_joyful" in the Stimulus_type column
    data1$Stimulus_type <- ifelse (data1$Stimulus_type=="stim_MJ01.jpg"
                                  |data1$Stimulus_type=="stim_MJ02.jpg"
                                  |data1$Stimulus_type=="stim_MJ03.jpg"
                                  |data1$Stimulus_type=="stim_MJ04.jpg"
                                  |data1$Stimulus_type=="stim_MJ05.jpg"
                                  |data1$Stimulus_type=="stim_MJ06.jpg"
                                  |data1$Stimulus_type=="stim_MJ07.jpg"
                                  |data1$Stimulus_type=="stim_MJ08.jpg"
                                  |data1$Stimulus_type=="stim_MJ09.jpg"
                                  |data1$Stimulus_type=="stim_MJ10.jpg","male_joyful", data1$Stimulus_type)

    #Same for WJ
    data1$Stimulus_type <- ifelse (data1$Stimulus_type=="stim_WJ01.jpg"
                                   |data1$Stimulus_type=="stim_WJ02.jpg"
                                   |data1$Stimulus_type=="stim_WJ03.jpg"
                                   |data1$Stimulus_type=="stim_WJ04.jpg"
                                   |data1$Stimulus_type=="stim_WJ05.jpg"
                                   |data1$Stimulus_type=="stim_WJ06.jpg"
                                   |data1$Stimulus_type=="stim_WJ07.jpg"
                                   |data1$Stimulus_type=="stim_WJ08.jpg"
                                   |data1$Stimulus_type=="stim_WJ09.jpg"
                                   |data1$Stimulus_type=="stim_WJ10.jpg","female_joyful", data1$Stimulus_type)
    #Same for MN
    data1$Stimulus_type <- ifelse (data1$Stimulus_type=="stim_MN01.jpg"
                                  |data1$Stimulus_type=="stim_MN02.jpg"
                                  |data1$Stimulus_type=="stim_MN03.jpg"
                                  |data1$Stimulus_type=="stim_MN04.jpg"
                                  |data1$Stimulus_type=="stim_MN05.jpg"
                                  |data1$Stimulus_type=="stim_MN06.jpg"
                                  |data1$Stimulus_type=="stim_MN07.jpg"
                                  |data1$Stimulus_type=="stim_MN08.jpg"
                                  |data1$Stimulus_type=="stim_MN09.jpg"
                                  |data1$Stimulus_type=="stim_MN10.jpg","male_neutral", data1$Stimulus_type)
    #Same for WN
    data1$Stimulus_type <- ifelse (data1$Stimulus_type=="stim_WN01.jpg"
                                  |data1$Stimulus_type=="stim_WN02.jpg"
                                  |data1$Stimulus_type=="stim_WN03.jpg"
                                  |data1$Stimulus_type=="stim_WN04.jpg"
                                  |data1$Stimulus_type=="stim_WN05.jpg"
                                  |data1$Stimulus_type=="stim_WN06.jpg"
                                  |data1$Stimulus_type=="stim_WN07.jpg"
                                  |data1$Stimulus_type=="stim_WN08.jpg"
                                  |data1$Stimulus_type=="stim_WN09.jpg"
                                  |data1$Stimulus_type=="stim_WN10.jpg","female_neutral", data1$Stimulus_type)
    
    
    #Creating column for Gender of stimulus
    data1$Gender_stim <- data1$Stimulus_type
    
    data1$Gender_stim <- ifelse(data1$Gender_stim=="male_neutral"
                                |data1$Gender_stim=="male_joyful", "male", "female")

    
    #Creating column for Gender of stimulus
    data1$Emotion <- data1$Stimulus_type
    
    data1$Emotion<- ifelse(data1$Emotion=="male_neutral"
                                |data1$Emotion=="female_neutral", "neutral", "joyful")

    
    
     #Calling the "Du går"-scenario "safety1" in the Scenario_type column
    data1$Scenario_type_specific <- ifelse (data1$Scenario_type_specific=="Du går alene på gaden om aftenen. Personen på billedet kommer op til dig og vil stille dig et spørgsmål. Hvor tilbøjelig er du til at stole på personen på billedet i denne situation?"
                              ,"safety1", data1$Scenario_type_specific)
    
    #Same for "Denne person"
    data1$Scenario_type_specific <- ifelse (data1$Scenario_type_specific=="Denne person sælger et møbel på Den Blå Avis, som du gerne vil købe. Personen siger, at du kan få det, hvis du har mulighed for at hente det på deres private adresse. Hvor tilbøjelig er du til at stole på personen på billedet i denne situation?"
                              ,"safety2", data1$Scenario_type_specific)
    #Same for "Du kan "
    data1$Scenario_type_specific <- ifelse (data1$Scenario_type_specific=="Du kan ikke selv løse en matematisk opgave, og du er derfor nødt til at spørge om hjælp. Hvor tilbøjelig er du til stole på at personen på billedet kan hjælpe dig med opgaven?"
                              ,"capabilities3", data1$Scenario_type_specific)
    #Same for "Du skal"
    data1$Scenario_type_specific <- ifelse (data1$Scenario_type_specific=="Du skal have foretaget en knæoperation under fuld narkose. Personen på billedet er lægen som skal foretage operationen. Hvor tilbøjelig er du til at stole på personen på billedet til at foretage operationen?"
                              ,"capabilities4", data1$Scenario_type_specific)
    
   
    
        #Creating column for Gender of stimulus
    data1$Scenario_type <- data1$Scenario_type_specific
    
    data1$Scenario_type<- ifelse(data1$Scenario_type=="safety1"
                                |data1$Scenario_type=="safety2", "safety", "capabilities")
    
    
     #Renaming for consistensy
    data1 <- data1 %>%
      rename(
        Stimulus = stimuli,
        Scenario = scenario,
        Date = date)

    #Anonymizing data
    data1$ID <- sapply(data1$ID, digest::digest, algo = "crc32")  
    
    data1$Gender_par <-tolower(data1$Gender_par)
     
    data1$Gender_par <-ifelse(data1$Gender_par=="kvinde", "female", data1$Gender_par)
    data1$Gender_par <-ifelse(data1$Gender_par=="mand", "male", data1$Gender_par)
    
       
    #selecting the columns we want to keep in the dataframe
    data1 <- data1 %>%
      select(
        ID, Age, Gender_par, Emotion, Gender_stim, Trial, Trust_rating, Date, Stimulus, Stimulus_type, Scenario, Scenario_type, Scenario_type_specific
        )

    #Omitting data that is NA 
    data1 <- na.omit(data1)
    
    
    return(data1)
}


# test it on just one file while writing the function
#test_data <- read_files(list[3])


# mapping a df with all the files
df = list %>%
    purrr::map_df(read_files)

#writing a csv of the dataframe 
write.csv(df,'DF_exam_data.csv')

```



```{r loading more libraries}
library(tidyverse)
library(ggplot2)
library(brms)

#Reloading df
#df <- read.csv("DF_exam_data.csv")

#Scaling outcome variable
df$Trust_rating_scaled<- (df$Trust_rating - mean(df$Trust_rating)) / sd(df$Trust_rating)

```


#Part 2: MODELS
```{r MODELS}

#get_prior(data = df, family = gaussian(), Trust_rating ~ 1 + Scenario_type*Gender_stim + Gender_par + Emotion + (1|Gender_par) + (1|ID))

#M1##############################################
m1_prior <-
  brm(data = df,
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Gender_stim*Scenario_type + Gender_par + Emotion + (1|Gender_par) + (1| ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      cores=2,
      sample_prior = "only",
      control = list(adapt_delta = 0.999, max_treedepth = 15))

pp_check(m1_prior, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("Figure 1 - M1 Prior Predictive Check")



m1 <-
  brm(data = df,
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Gender_stim*Scenario_type + Gender_par + Emotion + (1|Gender_par) + (1| ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      cores = 2,
      sample_prior = TRUE,
      control = list(adapt_delta = 0.999, max_treedepth = 15))

pp_check(m1, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("Figure 2 - M1 Posterior Predictive Check")

summary(m1)

#M2######################################################

m2 <- 
  brm(data = df, 
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Gender_stim*Scenario_type + Gender_par + Emotion + (1|ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      cores = 4,
      sample_prior = TRUE,
      control = list(adapt_delta = 0.999, max_treedepth = 15))

pp_check(m2, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("M2 - Posterior Predictive Check")

#M3######################################################


m3 <- 
  brm(data = df, 
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Gender_stim*Scenario_type + Emotion + (1|ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      cores = 4,
      sample_prior = TRUE,
      control = list(adapt_delta = 0.99, max_treedepth = 15))

pp_check(m3, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("M3 - Posterior Predictive Check")


#M4####################################################

m4 <- 
  brm(data = df, 
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Gender_stim*Scenario_type + Emotion + (1|Gender_par) + (1|ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      iter = 2500,
      cores = 4,
      sample_prior = TRUE,
      control = list(adapt_delta = 0.99, max_treedepth = 15))

pp_check(m4, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("M4 - Posterior Predictive Check")


#M5####################################################

m5 <- 
  brm(data = df, 
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Emotion*Scenario_type + Gender_par + Gender_stim + (1|Gender_par) + (1|ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      cores = 4,
      sample_prior = TRUE,
      control = list(adapt_delta = 0.999, max_treedepth = 15))

summary(m5)

pp_check(m5, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("M5 - Posterior Predictive Check")

#M6####################################################

m6 <- 
  brm(data = df, 
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Emotion*Scenario_type + Gender_par + Gender_stim + (1|ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      cores = 4,
      sample_prior = TRUE,
      control = list(adapt_delta = 0.99, max_treedepth = 15))

pp_check(m6, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("M6 - Posterior Predictive Check")


#M7####################################################

m7_prior <- 
  brm(data = df, 
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Emotion*Scenario_type + Gender_stim + (1|ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      iter = 3000,
      cores = 4,
      sample_prior = "only",
      control = list(adapt_delta = 0.99, max_treedepth = 15))

pp_check(m7_prior, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("Figure 3 - M7 Prior Predictive Check")

m7 <- 
  brm(data = df, 
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Emotion*Scenario_type + Gender_stim + (1|ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      iter = 3000,
      cores = 4,
      sample_prior = TRUE,
      control = list(adapt_delta = 0.99, max_treedepth = 15))

pp_check(m7, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("Figure 4 - M7 Posterior Predictive Check")

summary(m7)


#M8######################################################


m8 <- 
  brm(data = df, 
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Emotion*Scenario_type + Gender_stim + (1|Gender_par) + (1|ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      cores = 4,
      sample_prior = TRUE,
      control = list(adapt_delta = 0.99, max_treedepth = 15))

pp_check(m8, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("M8 - Posterior Predictive Check")


#M9######################################################

m9 <- 
  brm(data = df, 
      family = gaussian(),
      Trust_rating_scaled ~ 1 + Gender_par + Emotion + Scenario_type + Gender_stim + (1|Gender_par) + (1|ID),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(1), class = sd),
                prior(normal(1, 0.5), class = sigma)),
      cores = 4,
      sample_prior = TRUE,
      control = list(adapt_delta = 0.99, max_treedepth = 15))

pp_check(m9, nsamples = 100)+
  xlim(-20,20)+
  ggtitle("M9 - Posterior Predictive Check")


summary(m9)

```


#Part 3: PLOTS
```{r PLOTS}

library("bayesplot")

#HYPOTHESIS 1 + 2 - Posterior predictive check 

color_scheme_set("red")

post <- posterior_samples(m1)

post %>% 
  select(starts_with("b_")) %>% 
  mcmc_intervals(prob = .95,
                 point_est = "mean") +
  labs(title = "Trust ratings") +
  theme_bw() +
  theme(axis.text.y = element_text(hjust = 0),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank())


#HYPOTHESIS 3 + 4 - Posterior predictive check
post_m7 <- posterior_samples(m7)

post_m7 %>% 
  select(starts_with("b_")) %>% 
  mcmc_intervals(prob = .95,
                 point_est = "mean") +
  labs(title = "M7 - Trust ratings") +
  theme_bw() +
  theme(axis.text.y = element_text(hjust = 0),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank())


#Hypothesis 1
plot(hypothesis(m1,"Gender_stimmale>0")) 
 
#Hypothesis 2
plot(hypothesis(m1,"Scenario_typesafety>0")) 

#Hypothesis 3
plot(hypothesis(m7,"Scenario_typesafety>0"))

#hypothesis 4 
plot(hypothesis(m7,"Emotionneutral>0"))


summary(m7)

#HYPOTHESIS 1+2 - Gender_stim and Scenario type
ggplot(data=df, aes(x=Trust_rating)) + 
      geom_bar(aes(y = ..prop.., fill = Gender_stim), position = "dodge")+
  facet_wrap(.~Scenario_type)+
  theme_linedraw()


#HYPOTHESIS 3+4 - Emotion and Scenario type
ggplot(data=df, aes(x=Trust_rating)) + 
      geom_bar(aes(y = ..prop.., fill = Emotion), position = "dodge")+
  facet_wrap(.~Scenario_type)+
  theme_linedraw()







ggplot(data=df, aes(x=Trust_rating)) + 
      geom_bar(aes(y = ..prop.., fill = Gender_stim), position = "dodge")+
  facet_wrap(.~Scenario_type+Gender_par)+
  theme_linedraw()


#SECONDARY RESULTS - Gender_stim and Scenario type + Gender of participant
ggplot(df, aes(Trust_rating, fill = Gender_stim))+
  geom_bar(position= "dodge")+
  facet_wrap(.~Scenario_type+Gender_par)+
  theme_linedraw()

#SECONDARY RESULTS - Emotion and scenariotype_specific 
ggplot(df, aes(Trust_rating, fill = Emotion))+
  geom_bar(position= "dodge")+
  facet_wrap(.~Scenario_type)+
  theme_linedraw()


#SECONDARY RESULTS - Emotion and scenariotype_specific 
ggplot(df, aes(Trust_rating, colour = Emotion))+
  geom_density()+
  facet_wrap(.~Scenario_type)+
  theme_linedraw()


```


#Part 4: Comparing models
```{r Comparing models}

summary(m1)  #0
summary(m2)  #0
summary(m3)  #0
summary(m4)  #13 divergent transitions
summary(m5)  #0
summary(m6)  #0
summary(m7)  #0
summary(m8)  #1 divergent transition
summary(m9)  #75 divergent transitions
#making loo comparison

m1 <- add_criterion(m1, "loo")
m2 <- add_criterion(m2, "loo")
m3 <- add_criterion(m3, "loo")
#m4 <- add_criterion(m4, "loo")
m5 <- add_criterion(m5, "loo")
m6 <- add_criterion(m6, "loo")
m7 <- add_criterion(m7, "loo")
#m8 <- add_criterion(m8, "loo")
#m9 <- add_criterion(m9, "loo")

loo_compare( m1, m2, m3, m5, m6, m7, criterion = "loo") %>% 
  print(simplify = F)

```
  
  
#Participant info
```{r Participant info}

min(df$Age)

max(df$Age)

mean(df$Age)

sd(df$Age)

```
